link_to_paragraph.config:
  type: config_entity
  label: 'Configure link to paragraph'
  mapping:
    paragraph:
      type: string
      label: 'Paragraph field'
    node_field:
      type: string
      label: 'Node field with paragraph'
